version: '3'

services:
  fastapi_rag_system:
    build:
      context: ./ 
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - react_rag_app

  react_rag_app:
    build:
      context: ./client
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"
